import geopandas
import pandas as pd

from scripts.families.utils import LanguageNotFound
from scripts.predictors.polygons.glottography import PolygonNotFoundException, LiterallyNoPolygonException

AUSTRALIA_POLYS_DIR = 'data/glottography/australia'
POLYS_LIST = 'pamanyungan-polygons.csv'


class PamaNyunganPolygons:
    def __init__(self, geodesic=True):
        # Read in list of Pama-Nyungan polygons generated by inventory script
        self.polygon_list = pd.read_csv(f'{AUSTRALIA_POLYS_DIR}/{POLYS_LIST}', keep_default_na=False)
        self.sources = self.initialise_sources(geodesic)

    def get_polygon_from_ascii(self, family, ascii):
        # Get polygon meta from inventory
        row = self.polygon_list[self.polygon_list.language_id == ascii]
        if row.empty:
            raise LanguageNotFound(ascii)
        poly_file = row.polygon_file.values[0]
        poly_name = row.polygon_name.values[0]

        # Check a polygon exists
        if poly_file == '':
            raise LiterallyNoPolygonException(ascii)

        # Read polygon from necessary source file
        source = self.sources[poly_file]
        polygon = source[source.Name == poly_name]
        if len(polygon) == 0:
            raise PolygonNotFoundException(ascii, poly_file)
        return polygon

    def initialise_sources(self, geodesic=True):
        # Get list of source files
        source_files = set(self.polygon_list.polygon_file)
        source_files.remove('')

        # Read each file and store in dict
        sources = {}
        for source_file in source_files:
            source_df = geopandas.read_file(f'{AUSTRALIA_POLYS_DIR}/{source_file}')
            if geodesic:
                source_df = source_df.to_crs('EPSG:32633')
            sources[source_file] = source_df
        return sources


if __name__ == '__main__':
    pamanyungan = PamaNyunganPolygons()
    polygon = pamanyungan.get_polygon_from_ascii(None, 'Iyora')
    print(polygon)
